theme: magazine
pages_order_by: date
author: Ankit Juneja
authordescription: Senior Software Developer at DataChannel.co
site_title: Zobyo
numPerPage: 12
rewrite_url: true
authorgithub: https://github.com/devankitjuneja
authorlinkedin: https://www.linkedin.com/in/ankit-juneja-a16b5647
authoremail: "mailto: ankitjuneja@gmx.com"
copyright_year: 2020
authorimage: /assets/img/Ankit.jpg
authorimagealt: /assets/img/Ankit-alt.jpg
